sudo: false
dist: trusty
language: php
cache:
  apt: true
  directories:
    - node_modules
    - vendor
    - $HOME/.composer/cache
env:
  global:
    - WP_TRAVISCI=travis:phpunit
matrix:
  include:
  - php: 7.1
    env: WP_TRAVISCI=travis:js
  - php: 7.2
  - php: 7.1
  - php: 7.0
    env: WP_TEST_REPORTER=true
  - php: 5.6
  - php: 5.6
    env: WP_TRAVIS_OBJECT_CACHE=true
    services: memcached
  - php: 5.5
  - php: 5.4
  - php: 5.3
    dist: precise
  - php: 5.2
    dist: precise
  - php: nightly
  allow_failures:
  - php: nightly
